server:
  port: 8080
spring:
  application:
    name: student-information-mangament
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student-information-mangament?serverTimezone=GMT%2b8
    username: root
    password: dly19720815.
mybatis-plus:
  configuration:
    #???????????????????????????????????????
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
student:
  path: D:\IDEA编程软件\student-information-mangament\img\
